stages:
  training_pipeline:
    cmd: set PYTHONPATH=src && python -m employee.pipeline.Training_pipeline
    deps:
      - Notebook_Experiments/Data/employee_data.csv
      - src/employee/components/Data_ingestion.py
      - src/employee/components/Data_validation.py
      - src/employee/components/Data_transformation.py
      - src/employee/components/Model_trainer.py
      - src/employee/components/Model_evaluation.py
    outs:
      - Artifacts/raw_data.csv
      - Artifacts/Data_validation/data_summary.txt
      - Artifacts/Data_validation/missing_summary.csv
      - Artifacts/Data_validation/unique_values.txt
      - Artifacts/Data_validation/duplicate_check.txt
      - Artifacts/data_transformation/cleaning_report.txt
      - Artifacts/data_transformation/t_test_results.txt
      - Artifacts/data_transformation/outlier_info.txt
      - Artifacts/data_transformation/skewness_before_boxcox.txt
      - Artifacts/data_transformation/df_final.csv
      - Artifacts/data_transformation/X_train_scaled.csv
      - Artifacts/data_transformation/y_resampled.csv
      - Artifacts/data_transformation/X_test_scaled.csv
      - Artifacts/data_transformation/y_test.csv
      - Artifacts/data_transformation/Preprocessor.pkl
      - Artifacts/models/Best_Model.pkl
      - Artifacts/evaluation/classification_report.txt
      - Artifacts/evaluation/confusion_matrix.npy
      - Artifacts/evaluation/evaluation_metrics.txt

  prediction_pipeline:
    cmd: set PYTHONPATH=src && python -m employee.pipeline.Prediction_pipeline
    deps:
      - src/employee/pipeline/Prediction_pipeline.py
      - Artifacts/models/Best_Model.pkl
      - Artifacts/data_transformation/Preprocessor.pkl
    outs:
      - Artifacts/predictions/prediction_results.json
